### ISSUE TITLE
Adapt README and documentation for Github?

### ISSUE THREAD

**Issue by ppKrauss** [Tekki/sql-ledger#3]
I can help, there are interest in add some markdown documentation? 

... Starting with a basic "install guide"

**Comment by Tekki** [comment]
It's correct, such a documentation is missing and of course, if you have time, you're invited to help.
Before you start, consider the following: There are a lot of different Linux distributions, to write something 'basic' that fits all of them is nearly impossible. On the other hand, the more you write, the more you have to maintain.
Then, there's the Ansible role https://github.com/Tekki/ansible-sql-ledger that should be mentioned in the guide. Instead of having a lot of instructions I would prefer to see this role work with more distributions too, at least Ubuntu and openSUSE.

**Comment by ppKrauss** [comment]
Hi @Tekki, we are looking for a "definitive option", so I must wait a decision to start a help and tests... 

About *"(...) a lot of different Linux distributions, to write something 'basic' that (...)"* today we focus on main distribuitions, and, in the case of SQL-Ledger, Server Linux. The most popular are Debian Stable and UBUNTU LTS, so *.deb* installations &mdash; so, summing, deb's followed very far by  the next,  RedHat server... As the most discussed and document in the internet is UBUNTU, we use as reference installation the UBUNTU 16 LTS (Xenial). It is sufficient as "third party testing and revision" of a system.
