### ISSUE TITLE
Login issue after the pull of the 3.2.7 version

### ISSUE THREAD

**Issue by gakmalone** [Tekki/sql-ledger#31]
Hi,
I've get login issue after the pull of this new version ?
Is there a regression ?
Regards

**Comment by Tekki** [comment]
Do you get a 'permission denied' error on the images folder? If yes, run `chown www-data:www-data images` (on Debian). If not, please give some more details.

**Comment by gakmalone** [comment]
It was my old sql-ledger.conf 
The $helpful_login var  is missed !
Rgds

**Comment by Tekki** [comment]
I was just going to ask from which version you upgraded, because this was one of the suspects (the other was a change in 3.2.7). Please notice that I've disabled the 'helpful login' because I consider it to be a security risk on all networks where there is no strict control about who is allowed to connect to the server.
