### ISSUE TITLE
UTF-8 vs Binary

### ISSUE THREAD

**Issue by Tekki** [Tekki/sql-ledger#4]
In DBD::Pg > 3.2.1 binary strings are in some cases converted to UTF-8. There is an open issue on RT since 2015: https://rt.cpan.org/Public/Bug/Display.html?id=103137
It seems this will never be solved in DBD::Pg, so the solution can only be to modify SQL-Ledger to make it work consistently with Unicode, as described in http://perldoc.perl.org/perlunicode.html.

ping @lkraav

**Comment by lkraav** [comment]
Thanks for the initiative @Tekki, I got hung up with some stuff. Will look to share my current findings here today/tomorrow. I will paste a little bit unorganized version here from what I typed up into sql-ledger forum, right now though.

It is still really difficult to get correct UTF-8 working with modern DBD-Pg.

Based on research and tons of testing, I'm fairly certain the path forward includes the following:

Apache:
```
SetEnv LANG et_EE.utf8
SetEnv PGCLIENTENCODING UTF8
SetEnv PERL_UNICODE ASL
```

SQL-Ledger:
Needs to insert `use utf8;` in all its programs. `locale/` templates definitely need it for display, otherwise `PERL_UNICODE` setting will break.

DBD-Pg:
Needs to learn to save UTF-8 data into the database, I'm fairly certain it's plain broken. No configuration scenario that I could think of was able to save the word "tööd" as "tööd" in Postgres (as verified by `psql`), instead it gets saved as "tÂ¶Â¶d" or even worse - encoded multiple times like "tÃ&#131;Â¶Ã&#131;Â¶d".

If anyone has further ideas who's more unicode-broken here, SQL-Ledger or DBD-Pg, I'd appreciate your thoughts.

Could SL::Form::escape() and unescape() be involved here? These look like incredibly risky replacement operations for unicode.

With a full modern Unicode stack setup, we need to manually encode/decode after escaping. This is how form input gets saved into the database in normal UTF-8 form.

```
package Form;
use Encode;
use utf8;

sub escape {
...

$str = encode('UTF-8', $str);
$str =~ s/([^a-zA-Z0-9_.-])/sprintf("%%%02x", ord($1))/ge;

...

}


sub unescape {
...

$str =~ s/%([0-9a-fA-Z]{2})/pack("c",hex($1))/eg;
$str = decode('UTF-8', $str);

...
}
```

**Comment by lkraav** [comment]
I believe the next step would be to set up some kind of a sandbox environment where we could easily test the updated UTF-8 behavior with a variety of patches and some example datasets.

**Comment by Tekki** [comment]
I've seen your posts in the SL forum. Partially I agree with your approach, partially I don't. Especially I think we have to solve everything inside the code, not using any environment variables. Otherwise we will interfere with other applications on the server. Apache - Perl - UTF-8 work perfectly fine if the code is correct.
Now the starting point is definitely the database connection. It's quite straightforward (at least I hope so): just don't use any parameters. This will break the application at many places, but only at the beginning. If we start somewhere else, we will have to start from scratch again and again.
Next will be the communication with the browser, a) data sent to the browser, b) data received from the browser.
After this, we can care about the other areas: translations, templates, config files and so on.

I can create a new branch for the testing. And we can open an issue for every new step.

A hint: Don't believe what you see, especially with Latin-1. Perl often falls back to Latin-1, so things may look correct, but aren't. In my applications, I usually run tests with Hungarian names. And then some console programs are too intelligent and change the encoding on the fly. Print to text files and open them with Emacs seems to be the most secure way to determine what's going on.

And some history: It's now 5 years that I've pointed out at a conference the problems we have in SQL-Ledger with character encodings. Obviously not everything is as urgent as it appears to programmers.

**Comment by lkraav** [comment]
> Partially I agree with your approach, partially I don't. Especially I think we have to solve everything inside the code, not using any environment variables. Otherwise we will interfere with other applications on the server. Apache - Perl - UTF-8 work perfectly fine if the code is correct.

I actually agree with this myself. Since my perl-fu is super limited, I had to find the quickest way available to make environment-global settings work, and apache `SetEnv` works for that.

We can and certainly should eliminate any web server level configuration workload.

> Now the starting point is definitely the database connection. It's quite straightforward (at least I hope so): just don't use any parameters. This will break the application at many places, but only at the beginning. If we start somewhere else, we will have to start from scratch again and again.

Yes, exactly. I think DBD::Pg is actually now doing the right things with their v3 utf rewrite, so now it's up to SL to stop messing things up with its legacy custom escaping system.

> Next will be the communication with the browser, a) data sent to the browser, b) data received from the browser.

Here Dieter himself already made an effort forward with tail end of the v3 releases - you can select UTF-8 in user settings and it makes a difference to output. This is probably only step 1 out of 10 though :)

But of course the SL HTML templating system itself is such a huge crazy mess, I am not surprised at all why LedgerSMB people simply rewrote everything.

> I can create a new branch for the testing. And we can open an issue for every new step.

Perfect, let's start taking it step by step.

> A hint: Don't believe what you see, especially with Latin-1. Perl often falls back to Latin-1, so things may look correct, but aren't. In my applications, I usually run tests with Hungarian names. And then some console programs are too intelligent and change the encoding on the fly. Print to text files and open them with Emacs seems to be the most secure way to determine what's going on.

Absolutely correct - I check and see all necessary details in `vim`.

> And some history: It's now 5 years that I've pointed out at a conference the problems we have in SQL-Ledger with character encodings. Obviously not everything is as urgent as it appears to programmers.

SL is such an ancient program, people have so much invested over the year, they would rather not even poke the bear, especially since it's somewhat possible to make it work as is.

I just found it ridiculous that the database was getting `tÂ¶Â¶d`, and since my operation is still small and flexibles, and I understand the problem domain, decided to take a shot at it. Someone has to be the firestarter sooner or later, maybe it will be us this time.

**Comment by Tekki** [comment]
The new branch is [utf8_devel](https://github.com/Tekki/sql-ledger/tree/utf8_devel).

**Comment by Tekki** [comment]
And here's the issue for the first step: #5

**Comment by Tekki** [comment]
There is one important decision to make: That we switch completely to UTF-8. Do you agree?
This means for example no more translations in ISO charsets.

**Comment by lkraav** [comment]
> There is one important decision to make: That we switch completely to UTF-8. Do you agree?
This means for example no more translations in ISO charsets.

That's completely fine with me.

One thing I've learned, with limited manpower (which it always is in this business) - decisions, not options. Must cut dead weight.

**Comment by Tekki** [comment]
We have two following issues: #6 for output to and #7 input from browser.

**Comment by Tekki** [comment]
Next steps are translations (#8) and LaTeX templates (#9).

**Comment by Tekki** [comment]
And to continue: User config files (#10), e-mails (#11), new databases (#12).

**Comment by Tekki** [comment]
I consider this issue as 98 % solved. Waiting for feedback.

**Comment by Tekki** [comment]
23 days and no error report. So maybe it's time to think positive and round the 98 % up to 100?

**Comment by lkraav** [comment]
> 23 days and no error report. So maybe it's time to think positive and round the 98 % up to 100?

I've gotten overloaded with some customer stuff, but will definitely find a hole somewhere to get a feedback round in.

**Comment by lkraav** [comment]
Thanks a ton @Tekki

**Comment by lkraav** [comment]
Finally got enough brainspace for `git rebase Tekki/full` conversion, and everything seems to be working well :100: (since I had my db converted to UTF-8 already earlier).

**Comment by Tekki** [comment]
Thanks for the feedback!
