### ISSUE TITLE
Upgrading to Version 3.2.9 ... sql/Tekki-upgrade-011-015.sql:1 - ERROR: syntax error at or near "NOT" vs PostgreSQL 9.5

### ISSUE THREAD

**Issue by lkraav** [Tekki/sql-ledger#47]
Getting this at login:

```
Upgrading to Version 3.2.9 ... sql/Tekki-upgrade-011-015.sql:1 - ERROR: syntax error at or near "NOT"
LINE 1: ALTER TABLE bank ADD COLUMN IF NOT EXISTS qriban varchar(34)
^
```

https://stackoverflow.com/a/60311756/35946 seems to indicate it's not valid syntax, at least for 9.5?

**Comment by Tekki** [comment]
`ADD COLUMN IF NOT EXISTS` works since version 9.6 that was release in 2016. If you are on 9.5 you should replace the first line of `sql/Tekki-upgrade-011-015.sql` with
```
ALTER TABLE bank ADD COLUMN qriban varchar(34);
```
Do you know that version 9.5 reaches its end of life in February 2021? Maybe you should consider to upgrade to a more recent version.

**Comment by lkraav** [comment]
> `ADD COLUMN IF NOT EXISTS` works since version 9.6 that was release in 2016. If you are on 9.5 you should replace the first line of `sql/Tekki-upgrade-011-015.sql` with
> ```
> ALTER TABLE bank ADD COLUMN qriban varchar(34);
> ```

Yep, I ran that query manually. 

> Do you know that version 9.5 reaches its end of life in February 2021? Maybe you should consider to upgrade to a more recent version.

Thanks, yes, I will be upgrading.
